import Head from 'next/head'

import styles from '../styles/Home.module.css'
import Image from 'next/image'
import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, {
  Navigation
} from 'swiper';
import 'swiper/css';
import "swiper/css/navigation"

SwiperCore.use([Navigation]);

const Slider = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MovieBox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous' />
          <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap" rel="stylesheet"/>

      </Head>

        <div className={styles.slider}>
          <Swiper navigation={true} className="mySwiper" loop={true}>
            <SwiperSlide>Slide 1</SwiperSlide>
            <SwiperSlide>
              <Image src="/heroBanner.png" alt="MovieBox" width={500}
                     height={500}/>
            </SwiperSlide>
            <SwiperSlide>Slide 1</SwiperSlide>
            <SwiperSlide>Slide 1</SwiperSlide>
            <SwiperSlide>Slide 1</SwiperSlide>
          </Swiper>
        </div>

    </div>
  )
}



export default Slider
